### ISSUE TITLE
Fix Background Stephanie Page

### ISSUE THREAD

**Issue by stephanieb00** [masumahmed/assignment1#14]
For the stephanie.html page the background color of the body, so where all the text is written, is blanchedalmond, but the background color itself of the HTML file is black. This makes the page two different colors horizontally. Figuire out a way for the Stephanie page to just be blanchedalmond without messing with the colors of index.html.

**Comment by masumahmed** [comment]
right I changed the background color back to white in another branch.

**Comment by yumandee** [comment]
if we're not having a main theme, let's use a separate stylesheet for the main page and our individual pages

**Comment by stephanieb00** [comment]
Okay got it.
